name: Supply-chain security

on:
  branch_protection_rule:
  schedule:
    - cron: '45 4 * * 1'
  push:
    branches: [main, master]
  workflow_dispatch:

permissions: read-all

jobs:
  analysis:
    name: OpenSSF Scorecard
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      security-events: write
      id-token: write
      contents: read
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Run Scorecard analysis
        uses: ossf/scorecard-action@0864cf19026789058feabb7e87baa5f140aac736
        with:
          results_file: results.sarif
          results_format: sarif
          publish_results: true

      - name: Upload SARIF results
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: results.sarif

      - name: Upload Scorecard artifact
        uses: actions/upload-artifact@v4
        with:
          name: scorecard-results
          path: results.sarif
          if-no-files-found: error
          retention-days: 5
